Repository wecode-bootcamp-korea/13-Wellie-frontend, pull requests merged in 2020-11, with the labels that each got.

#2 [13기 Wellie 팀] Add: styled components 기본 세팅
  package-lock.json
  package.json
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/Styles/Theme.js
  src/Styles/common.scss
  src/Styles/mixin.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: Accepted

#6 [13기 Wellie 이동훈][feature/login] Refactor: 리팩토링 완료
  public/images/Login/apple_logo.png
  public/images/Login/fb_logo.png
  public/images/Login/kakao_logo.png
  public/images/Login/library1.jpeg
  public/images/Login/library2.jpeg
  public/images/Login/library3.jpeg
  public/images/Login/library4.jpeg
  public/images/Login/library5.jpeg
  public/images/Login/library6.jpeg
  public/images/Login/library7.jpeg
  public/images/Login/loginMain.jpeg
  public/images/Login/naver_logo.png
  public/images/gnb_logo.png
  public/images/gnb_logo_yellow.png
  public/images/logo_icon.png
  public/index.html
  src/Pages/Login/Join.js
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Login/SocialPlatforms.js
  src/Pages/Login/loginImagesData.js
  src/Pages/Login/loginNjoinSocialLogosData.js
  src/Pages/Payment/Payment.scss
  src/Pages/Signup/Signup.js
  src/Pages/Signup/Signup.scss
  src/Pages/Today/Today.js
  src/Pages/Today/Today.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#1 [13기 Wellie 홍효정] Add: 공통 navigation 추가
  .gitattributes
  package-lock.json
  package.json
  public/favicon.ico
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#3 [13기 Wellie 홍효정] 수정사항 반영, 도서 검색 기능 추가
  package-lock.json
  package.json
  public/data/MyBooks/BOOKLIST.json
  public/data/MyBooks/BOOKSHELFCASE.json
  public/data/MyBooks/BOOKSHELFLIST.json
  public/data/MyBooks/MYBOOKSINFO.json
  public/data/data.json
  public/images/MyBooks/millie_level1.png
  public/images/MyBooks/spl_input.png
  public/images/MyBooks/user.png
  src/Components/BookCard/BookCard.js
  src/Components/Nav/Nav.js
  src/Pages/MyBooks/Components/BookList.js
  src/Pages/MyBooks/Components/BookShelf.js
  src/Pages/MyBooks/Components/BookShelfList.js
  src/Pages/MyBooks/Components/FilterModal.js
  src/Pages/MyBooks/Components/Modal.js
  src/Pages/MyBooks/Components/ModalContent.js
  src/Pages/MyBooks/Components/PostList.js
  src/Pages/MyBooks/Components/StatsList.js
  src/Pages/MyBooks/Components/Style.js
  src/Pages/MyBooks/MyBooks.js
  src/Pages/MyBooks/MyBooks.scss
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/Styles/Theme.js
  src/config.js
Labels: Status: 리뷰 요청

#4 [13기 Wellie 백은진] Add: Main page 초기 레이아웃 구현
  package-lock.json
  package.json
  public/data/dataOfMain.json
  public/images/book1.png
  public/images/book2.png
  public/images/bookshelf1.png
  public/images/bookshelf2.png
  public/images/bookshelf3.png
  public/images/gift_box.png
  public/images/kimgoeun.png
  public/images/library.png
  public/images/logo_black.png
  public/images/logo_circle.png
  public/images/logo_yellow.png
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Search/Search.js
  src/Pages/WellieMain/Components/PriceCard.js
  src/Pages/WellieMain/Components/TestingAnimation.js
  src/Pages/WellieMain/Components/TextBox.js
  src/Pages/WellieMain/WellieMain.js
  src/Routes.js
Labels: Status: Accepted

#5 [13기 Wellie 최하늘] Fix: conflict 해결
  package-lock.json
  package.json
  public/data/BookDetails/books.json
  public/data/BookDetails/comment.json
  public/data/BookDetails/data.json
  public/index.html
  src/Pages/BookDetails/Aside.js
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookDetails/BookDetails.scss
  src/Pages/BookDetails/CommentSection.js
  src/Pages/BookDetails/Components/Book.js
  src/Pages/BookDetails/Components/Comment.js
  src/Pages/BookDetails/DescSection.js
  src/Pages/BookDetails/FinishBook.js
  src/Pages/BookDetails/IntroSection.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#13 [13 Wellie 최하늘] Add : 기능 구현 진행중
  package-lock.json
  src/Pages/BookDetails/Aside.js
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookDetails/CommentSection.js
  src/Pages/BookDetails/Components/Comment.js
  src/Routes.js
Labels: Status: 리뷰 요청

#9 [13기 Wellie 백은진] 카테고리 페이지 최종본
  .prettier.json
  package-lock.json
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookDetails/CommentSection.js
  src/Pages/Category/Category.js
  src/Pages/WellieMain/WellieMain.scss
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 진행중

#8 [13기 Wellie 홍효정] Modify: 공통 Nav, Route.js, Today.js 수정
  src/Components/Nav/Nav.js
  src/Routes.js
  src/Styles/GlobalStyle.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [13기 Wellie 홍효정] Modify: 수정 요청 리뷰반영
  public/data/MyBooks/BOOKSHELFCASE.json
  public/data/MyBooks/BOOKSHELFLIST.json
  public/data/MyBooks/BOOKSHELFLISTCARD.json
  public/images/MyBooks/empty_shelf.png
  src/Components/BookCard/BookCard.js
  src/Components/Nav/Nav.js
  src/Pages/MyBooks/Components/BookShelf.js
  src/Pages/MyBooks/Components/BookShelfList.js
  src/Pages/MyBooks/Components/FilterModal.js
  src/Pages/MyBooks/Components/Modal.js
  src/Pages/MyBooks/Components/ModalContent.js
  src/Pages/MyBooks/Components/Style.js
  src/Pages/MyBooks/MyBooks.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 진행중

#15 [13기 Wellie 백은진] Modify: 메인 페이지 최종본
  public/data/bookList.json
  public/data/dataOfMain.json
  src/Pages/Payment/Payment.js
  src/Pages/Payments/Payments.js
  src/Pages/Search/Components/InnerInput.js
  src/Pages/Search/Search.js
  src/Pages/Search/Search.scss
  src/Pages/Search/SearchResult.js
  src/Pages/WellieMain/Components/PriceCard.js
  src/Pages/WellieMain/Components/TestingAnimation.js
  src/Pages/WellieMain/Components/TextBox.js
  src/Pages/WellieMain/WellieMain.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 진행중

#17 [13기 Wellie 최하늘] Fix : conflict 해결
  public/data/BookDetails/contents.json
  src/Pages/BookDetails/Aside.js
  src/Pages/BookDetails/BookDetails.js
  src/Pages/BookDetails/CommentSection.js
  src/Pages/BookDetails/Components/Book.js
  src/Pages/BookDetails/Components/Comment.js
  src/Pages/BookDetails/Components/Page.js
  src/Pages/BookDetails/Components/Viewer.js
  src/Pages/BookDetails/DescSection.js
  src/Pages/BookDetails/FinishBook.js
  src/Pages/BookDetails/IntroSection.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#14 [13기 Wellie 홍효정] Add: 책장 추가 기능 구현
  src/Components/Nav/Nav.js
  src/Pages/MyBooks/Components/BookShelf.js
  src/Pages/MyBooks/Components/BookShelfList.js
  src/Pages/MyBooks/MyBooks.js
  src/Pages/MyBooksManager/MyBooksManager.js
  src/Routes.js
Labels: Status: 리뷰 요청

#18 [13기 Wellie 최하늘] Merge 후 conflict 해결
  src/Pages/BookDetails/BookDetails.js
  src/Routes.js
Labels: Status: Conflict 해결 요청

#16 [13기 Wellie 백은진] 검색 페이지 기본기능 구현 완료
  package-lock.json
  package.json
  src/Components/Nav/Nav.js
  src/Pages/Category/Category.js
  src/Pages/Search/Components/InnerInput.js
  src/Pages/Search/SearchDefault.js
  src/Pages/Search/SearchResult.js
  src/Pages/WellieMain/Components/PriceCard.js
  src/Pages/WellieMain/WellieMain.js
  src/Pages/WellieMain/WellieMain.scss
  src/Routes.js
  src/config.js
  src/index.js
  src/store/actions/index.js
  src/store/reducers/index.js
  src/store/reducers/searchReducer.js
Labels: Status: 리뷰 요청

#20 [13기 Wellie 백은진] Merge 후 지도 기능 삭제
  src/Pages/Search/Components/InnerInput.js
  src/Pages/Search/SearchResult.js
  src/Routes.js
Labels: Status: 리뷰 요청

#19 [13기 Wellie 최하늘] Fix : Merge 후 conflict 해결
  src/Routes.js
Labels: Status: 수정 요청

#22 [13기 Wellie 홍효정] Add: 책장 수정 기능 구현
  src/Pages/MyBooks/Components/BookShelf.js
  src/Pages/MyBooks/Components/BookShelfList.js
  src/Pages/MyBooksManager/MyBooksManager.js
  src/Routes.js
Labels: Status: 리뷰 요청

#23 [13 Wellie 이동훈] Fix: Kakao bug
  src/Pages/Login/components/SocialLoginComponents/KakaoLogin.js
Labels: Status: 리뷰 요청
